[package]
name = "fetchchromium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
indexmap = "1.9.2"
reqwest = { version = "0.11.13", features = ["blocking"] }
ripunzip = { path = "../ripunzip" }
serde = { version = "1.0.147", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.89"
